version: '3.7'
services:
  ignite-streaming-app:
    user: root
    image: ignite-compute-app
    container_name: ignite-compute-app
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '0.50'
    environment:
      - IGNITE_WORK_DIR=/opt/ignite/work
      - execTime=150
    networks:
      - ignite-net
    volumes:
      - ../config:/opt/ignite/ext-config
      - ../work:/opt/ignite/work

networks:
  ignite-net:
    driver: bridge
